import type { LearningBriefing } from "../types";

const SRC = { label: "학습을 위해 재구성한 예시예요." };

/** 학습용 브리핑. 실제 기사 문장을 옮기지 않음.
 * `reviewStatus: published`는 제품에 실렸다는 뜻이다. 사람 한국어·금융 검수 완료는 `copyReviewed`다.
 * 둘을 같은 값으로 쓰면 출고한 초안을 검수한 글로 착각한다.
 */
export const LEARNING_BRIEFINGS: LearningBriefing[] = [
  {
    id: "bf-cpi-rates",
    kicker: "물가·금리",
    minutes: 4,
    headline: "예상 웃돈 물가에 장기금리 상승…금리 인하 기대는 뒤로",
    subtitle: "물가 상승세가 예상보다 오래 이어질 수 있다는 해석이 나오면서 채권시장이 먼저 반응했어요.",
    primaryTermIds: ["소비자물가지수-cpi", "기준금리", "듀레이션"],
    supportTermIds: ["근원인플레이션율", "기대인플레이션"],
    sourceMode: "synthetic",
    contentMode: "synthetic",
    readingFormat: "market",
    reviewStatus: "published",
    difficulty: "core",
    sourceRefs: [SRC],
    evergreen: true,
    blocks: [
      {
        type: "p",
        text: "소비자물가 상승률이 시장 예상보다 높게 나왔어요. 발표 직후 장기 국채금리는 오르고, 이미 발행된 채권 가격은 하락했어요.",
      },
      {
        type: "p",
        text: "시장은 물가 압력이 예상보다 오래 이어지면 중앙은행이 기준금리를 빠르게 내리기 어려울 수 있다고 해석했어요.",
      },
      {
        type: "cloze",
        before: "물가 상승률이 예상보다 높게 나오면서 시장에서는 기준금리 인하 시점이 예상보다 ",
        after: " 수 있다는 전망이 커졌어요.",
        question: "물가가 예상보다 높게 나오면 기준금리 인하 시점은 어떻게 읽힐까요?",
        answerId: "late",
        choices: [
          { id: "late", label: "늦어질" },
          { id: "early", label: "빨라질" },
          { id: "fixed", label: "고정될" },
          { id: "gone", label: "사라질" },
        ],
        note: "물가 압력이 쉽게 낮아지지 않으면 중앙은행이 기준금리를 빠르게 내리기 어려워요. 그래서 인하 시점이 뒤로 밀릴 수 있어요.",
      },
      {
        type: "p",
        text: "다만 한 달의 소비자물가만으로 흐름을 단정하기는 어려워요. 식품·에너지처럼 변동이 큰 항목을 제외한 근원물가와 기대인플레이션도 함께 봐야 해요. 같은 폭으로 금리가 올라도 만기가 긴 채권일수록 가격이 더 크게 움직이는데, 이 차이를 듀레이션으로 설명해요.",
      },
      {
        type: "choice",
        depth: "term",
        question: "같은 폭으로 금리가 올랐는데 장기채 가격이 더 많이 떨어졌어요. 이 차이를 설명하는 개념은 무엇일까요?",
        answerId: "듀레이션",
        choices: [
          { id: "듀레이션", label: "듀레이션" },
          { id: "만기수익률", label: "만기수익률" },
          { id: "표면금리", label: "표면금리" },
          { id: "신용스프레드", label: "신용스프레드" },
        ],
        note: "만기가 길고 이자를 적게 주는 채권일수록 듀레이션이 길어요. 그래서 금리가 같은 폭으로 움직여도 장기채의 가격이 더 크게 떨어질 수 있어요.",
      },
      {
        type: "causal",
        title: "한 번에 연결하면",
        chain: ["물가 예상 상회", "금리 인하 기대 약화", "시장금리 상승 가능", "채권가격 하락 압력"],
      },
      {
        type: "choice",
        depth: "next",
        question: "한 달의 헤드라인 물가만으로 물가 흐름을 단정하기 어려운 이유는 무엇일까요?",
        answerId: "core",
        choices: [
          { id: "core", label: "근원물가와 기대인플레이션을 함께 봐야 흐름을 판단할 수 있다" },
          { id: "once", label: "헤드라인 물가 한 달이면 기조가 확정된다" },
          { id: "div", label: "헤드라인 물가가 한 달 오르면 기준금리도 그만큼 오른다" },
          { id: "ignore", label: "에너지 값이 오른 달은 근원물가도 반드시 같이 오른다" },
        ],
        note: "헤드라인 물가 한 달은 에너지 같은 일시 충격이 섞일 수 있어요. 근원물가가 같이 올랐는지를 봐야 해요.",
      },
      { type: "concepts", ids: ["소비자물가지수-cpi", "기준금리", "듀레이션"] },
    ],
  },
  {
    id: "bf-earnings-down",
    kicker: "실적·주가",
    minutes: 3,
    headline: "실적은 늘었는데 주가는 하락…시장은 기대와 비교했어요",
    subtitle: "지난 분기 숫자는 확인된 사실이고, 주가는 앞으로의 기대를 먼저 반영할 수 있어요.",
    primaryTermIds: ["주당순이익-eps", "주가수익비율-per", "rpt-consensus"],
    sourceMode: "synthetic",
    contentMode: "synthetic",
    readingFormat: "earnings",
    reviewStatus: "published",
    difficulty: "core",
    sourceRefs: [SRC],
    evergreen: true,
    blocks: [
      {
        type: "p",
        text: "한 기업의 지난 분기 영업이익이 전년보다 18% 늘었어요. 그런데 시장 예상치는 그보다 높았고, 실적 발표 당일 주가는 하락했어요.",
      },
      {
        type: "p",
        text: "시장은 주당순이익을 컨센서스와 먼저 비교했어요. 전년보다 좋아져도 기대에 못 미치면 실망 매물이 나올 수 있어요. 금리가 오르면 같은 이익에도 주가수익비율이 낮아질 수 있다는 해석도 붙었어요.",
      },
      {
        type: "p",
        text: "다만 당일 주가 한 줄만으로 실적 숫자가 틀렸다고 볼 수는 없어요. 확인된 것은 지난 분기 실적이고, 내년 이익과 목표주가는 아직 전망이에요.",
      },
      {
        type: "choice",
        depth: "cause",
        question: "지금 확인된 사실은?",
        answerId: "fact",
        choices: [
          { id: "fact", label: "지난 분기 영업이익이 전년보다 늘었다는 공시" },
          { id: "est", label: "내년에도 같은 속도로 이익이 늘어날 것이라는 전망" },
          { id: "cheap", label: "지금 주가가 저평가돼 있다는 의견" },
          { id: "buy", label: "목표주가를 올리고 매수를 유지한다는 추천" },
        ],
        note: "지난 실적 숫자는 확인된 내용이에요. 앞으로의 이익·목표가·매수는 아직 전망과 의견이에요.",
      },
      {
        type: "choice",
        depth: "next",
        question: "실적이 늘었는데도 ‘기대보다 부진했다’는 평가가 나왔어요. 가장 먼저 무엇과 비교해야 할까요?",
        answerId: "cons",
        choices: [
          { id: "cons", label: "컨센서스와 실제 실적의 차이" },
          { id: "pe", label: "PER는 실적 발표와 무관하므로 같이 보지 않는다" },
          { id: "guide", label: "회사가 내년 가이던스를 안 내면 기대는 없는 것과 같다" },
          { id: "price", label: "당일 주가가 내렸으면 실적 숫자는 틀린 것이다" },
        ],
        note: "주가는 과거 실적보다 앞으로 얼마를 벌 것으로 봤는지에 더 민감할 수 있어요.",
      },
      {
        type: "causal",
        title: "한 번에 연결하면",
        chain: ["공시된 실적", "시장 기대와의 차이", "금리·배수", "주가"],
      },
      { type: "concepts", ids: ["주당순이익-eps", "주가수익비율-per", "rpt-consensus"] },
    ],
  },
  {
    id: "bf-yoy-ytd",
    kicker: "숫자 읽기",
    minutes: 3,
    headline: "한 달은 +45%, 올해 누적은 +18%…비교 기간이 달랐어요",
    subtitle: "전년 동월 대비와 연초 누적은 같은 속도를 가리키지 않아요.",
    primaryTermIds: ["rpt-yoy", "rpt-ytd", "rpt-base"],
    sourceMode: "synthetic",
    contentMode: "synthetic",
    readingFormat: "earnings",
    reviewStatus: "published",
    difficulty: "core",
    sourceRefs: [SRC],
    evergreen: true,
    blocks: [
      {
        type: "p",
        text: "한 기업의 월 수출액이 전년 같은 달보다 45% 늘었어요. 반면 1월부터 현재까지의 누적 수출액은 전년 같은 기간보다 18% 늘었어요.",
      },
      {
        type: "p",
        text: "시장 일부는 한 달의 +45%만 보고 올해 내내 그 속도로 성장했다고 읽었어요. 그런데 전년 동월 대비와 연초 누적은 비교 기간이 달라요. 최근 한 달이 좋아도 앞선 달이 부진했다면 누적 증가율은 더 낮게 나와요.",
      },
      {
        type: "p",
        text: "다만 비율만으로 단정하기는 어려워요. 절대 금액이 작은지, 작년 같은 기간이 유난히 나빴는지 같은 기저효과도 함께 봐야 해요.",
      },
      {
        type: "choice",
        depth: "number",
        question: "왜 두 증가율이 다를 수 있을까요?",
        answerId: "period",
        choices: [
          { id: "period", label: "전년 동월 대비와 연초 누적은 비교 기간이 다르다" },
          { id: "same", label: "YoY와 YTD는 같은 기간을 보므로 항상 같아야 한다" },
          { id: "fxonly", label: "환율만 보면 두 비율은 자동으로 같아진다" },
          { id: "ignore", label: "누적이 낮으면 한 달 숫자는 오류다" },
        ],
        note: "YoY는 특정 기간을 전년 같은 기간과 비교하고, YTD는 연초부터 현재까지의 누적 실적을 비교해요. 최근 한 달의 증가율이 높아도 앞선 달의 증가율이 낮았다면 YTD는 더 낮을 수 있어요.",
      },
      {
        type: "choice",
        depth: "next",
        question: "증가율이 크게 보일 때 함께 확인하면 좋은 것은 무엇일까요?",
        answerId: "base",
        choices: [
          { id: "base", label: "절대 금액과 기저효과" },
          { id: "onlypct", label: "비율만 보면 충분하다" },
          { id: "mom", label: "전월 대비만 보면 YoY는 필요 없다" },
          { id: "skip", label: "한 달 숫자가 크면 누적은 보지 않아도 된다" },
        ],
        note: "비율만 보면 착시가 날 수 있어요. 금액의 크기와 작년 같은 기간이 유난히 나빴는지도 같이 봐요.",
      },
      {
        type: "causal",
        title: "한 번에 연결하면",
        chain: ["한 달 실적", "YoY", "YTD", "기저효과"],
      },
      { type: "concepts", ids: ["rpt-yoy", "rpt-ytd", "rpt-base"] },
    ],
  },
  {
    id: "bf-fx-export",
    kicker: "환율·수출",
    minutes: 3,
    headline: "원화 약세에 수출 환산액은 늘었지만, 수입 비용도 같이 커졌어요",
    subtitle: "환율만으로 수출 기업 실적을 단정하기는 어려워요.",
    primaryTermIds: ["평가절상", "경상수지"],
    sourceMode: "synthetic",
    contentMode: "synthetic",
    readingFormat: "industry",
    reviewStatus: "published",
    difficulty: "core",
    sourceRefs: [SRC],
    evergreen: true,
    blocks: [
      {
        type: "p",
        text: "원화가 약해지자 같은 달러 수출이 원화로 환산되며 더 커 보였어요. 동시에 수입 원자재 비용도 늘었다는 반응이 나왔어요.",
      },
      {
        type: "p",
        text: "시장은 수출 단가 효과와 물량을 나눠 봤어요. 환율이 유리해 보여도 해외 수요가 줄면 수출 물량이 빠질 수 있어요. 반대로 원화가 강해지는 평가절상은 수출 가격 경쟁력에는 부담이 되고 수입 물가 부담은 줄어들 수 있어요.",
      },
      {
        type: "p",
        text: "다만 환율 숫자 하나만으로 실적을 확정할 수는 없어요. 수출 물량과 수입 비용, 경상수지가 실제로 어떻게 움직였는지를 함께 확인해야 해요.",
      },
      {
        type: "choice",
        depth: "term",
        question: "자국 통화의 가치가 다른 통화보다 높아지는 것을 무엇이라고 할까요?",
        answerId: "평가절상",
        choices: [
          { id: "평가절상", label: "평가절상" },
          { id: "기준금리", label: "기준금리" },
          { id: "경상수지", label: "경상수지" },
          { id: "외환보유액", label: "외환보유액" },
        ],
        note: "평가절상은 자국 통화의 가치가 다른 통화보다 높아지는 것이에요. 수출 가격 경쟁력에는 부담이 되고, 수입 물가 부담은 줄어들 수 있어요.",
      },
      {
        type: "choice",
        depth: "next",
        question: "환율 다음에 함께 볼 것은 무엇일까요?",
        answerId: "ca",
        choices: [
          { id: "ca", label: "수출 물량, 수입 비용, 경상수지" },
          { id: "only", label: "환율 숫자 하나만" },
          { id: "always", label: "원화 약세면 수출 기업 실적은 항상 좋아진다" },
          { id: "ignore", label: "수입 원자재 비용은 환율과 무관하다" },
        ],
        note: "경상수지와 수출 물량을 봐야 환율 효과가 실적으로 남는지 가늠할 수 있어요.",
      },
      {
        type: "causal",
        title: "한 번에 연결하면",
        chain: ["환율", "수출 환산액", "수입 비용", "실적"],
      },
      { type: "concepts", ids: ["평가절상", "경상수지"] },
    ],
  },
  {
    id: "bf-jobs",
    kicker: "고용·금리",
    minutes: 3,
    headline: "실업률 오르자 금리 인하 기대가 커졌어요",
    subtitle: "일자리가 약해지면 성장과 물가 압력도 낮아질 수 있다는 해석이 나왔어요.",
    primaryTermIds: ["실업률", "고용률", "기준금리"],
    sourceMode: "synthetic",
    contentMode: "synthetic",
    readingFormat: "policy",
    reviewStatus: "published",
    difficulty: "core",
    sourceRefs: [SRC],
    evergreen: true,
    blocks: [
      {
        type: "p",
        text: "실업률이 오르자 고용 여건이 약해지고 있다는 신호가 먼저 읽혔어요.",
      },
      {
        type: "cloze",
        before: "발표 뒤 시장에서는 기준금리 인하 시점이 예상보다 ",
        after: " 수 있다는 전망이 커졌어요.",
        question: "실업률이 오르면 기준금리 인하 시점은 어떻게 읽힐까요?",
        answerId: "early",
        choices: [
          { id: "early", label: "빨라질" },
          { id: "late", label: "늦어질" },
          { id: "fixed", label: "고정될" },
          { id: "gone", label: "사라질" },
        ],
        note: "고용이 약해지면 성장과 물가 압력도 낮아질 수 있다고 읽혀요. 그래서 인하 시점 기대가 앞당겨질 수 있어요. 다만 임금과 물가가 단단하면 그 기대가 바로 확정되지는 않아요.",
      },
      {
        type: "p",
        text: "시장은 경기와 물가 압력이 함께 낮아질 수 있다고 해석했어요. 다만 실업률은 구직을 포기한 사람을 빼기 때문에, 일자리 사정은 고용률을 같이 봐야 더 잘 보여요.",
      },
      {
        type: "p",
        text: "고용이 약해도 임금과 물가가 단단하면 중앙은행은 쉽게 금리를 내리지 않을 수 있어요. 한 달의 실업률만으로 금리 경로를 단정하기는 어려워요.",
      },
      {
        type: "choice",
        depth: "term",
        question: "일하려는 사람 가운데 일자리를 구하지 못한 사람의 비율을 나타내는 지표는 무엇일까요?",
        answerId: "실업률",
        choices: [
          { id: "실업률", label: "실업률" },
          { id: "고용률", label: "고용률" },
          { id: "경제성장률", label: "경제성장률" },
          { id: "소매판매", label: "소매판매" },
        ],
        note: "실업률은 경제활동인구 가운데 실업자가 차지하는 비율이에요. 구직 활동을 하지 않는 사람은 실업률 계산에서 빠질 수 있으므로 고용률 등 다른 지표도 함께 봐요.",
      },
      {
        type: "choice",
        depth: "next",
        question: "고용 숫자 하나만으로 금리 방향을 단정하기 어려운 이유는 무엇일까요?",
        answerId: "wage",
        choices: [
          { id: "wage", label: "임금, 구인 강도, 물가를 같이 봐야 한다" },
          { id: "one", label: "실업률 한 달이면 금리 경로가 확정된다" },
          { id: "same", label: "실업률과 고용률은 같은 지표이므로 하나만 보면 된다" },
          { id: "ignore", label: "구직 포기자는 고용 판단에 넣을 필요가 없다" },
        ],
        note: "고용이 약해도 임금과 물가가 단단하면 중앙은행은 쉽게 금리를 내리지 않을 수 있어요.",
      },
      {
        type: "causal",
        title: "한 번에 연결하면",
        chain: ["고용 둔화", "성장 우려", "금리 인하 기대", "시장금리"],
      },
      { type: "concepts", ids: ["실업률", "고용률", "기준금리"] },
    ],
  },
  {
    id: "bf-capex",
    kicker: "투자·생산",
    minutes: 4,
    headline: "설비투자는 늘었는데 이익은 당장 안 늘었어요",
    subtitle: "공장과 장비에 돈이 먼저 나가고, 생산과 수요는 그다음에 따라와요.",
    primaryTermIds: ["자본적지출", "rpt-capa", "rpt-util"],
    sourceMode: "synthetic",
    contentMode: "synthetic",
    readingFormat: "industry",
    reviewStatus: "published",
    difficulty: "core",
    sourceRefs: [SRC],
    evergreen: true,
    blocks: [
      {
        type: "p",
        text: "한 기업이 공장과 장비에 대한 자본적지출을 늘렸다는 소식이 나왔어요. 현금은 먼저 나갔는데, 같은 분기 이익은 바로 늘지 않았어요.",
      },
      {
        type: "p",
        text: "장비 업체 쪽에서는 일감이 늘어날 것이라는 기대가 나왔어요. 다만 투자가 낡은 설비를 바꾸는 것인지, 생산능력을 늘리는 것인지에 따라 결과가 달라요. 설비가 늘어도 가동률이 낮으면 감가상각만 커질 수 있어요.",
      },
      {
        type: "p",
        text: "다만 투자 한 줄만으로 실적이 좋아진다고 단정할 수는 없어요. 생산능력이 실제로 늘었는지, 그 능력을 얼마나 돌리고 있는지를 함께 봐야 해요.",
      },
      {
        type: "choice",
        depth: "term",
        question: "공장·서버·장비처럼 장기간 사용하는 자산에 쓰는 투자 지출을 무엇이라고 할까요?",
        answerId: "자본적지출",
        choices: [
          { id: "자본적지출", label: "자본적지출 (CAPEX)" },
          { id: "주당순이익-eps", label: "주당순이익 (EPS)" },
          { id: "rpt-capa", label: "생산능력 (CAPA)" },
          { id: "rpt-util", label: "가동률" },
        ],
        note: "자본적지출(CAPEX)은 공장·서버·장비처럼 장기간 사용하는 자산에 쓰는 투자 지출이에요.",
      },
      {
        type: "choice",
        depth: "term",
        question: "설비투자로 생산할 수 있는 양이 얼마나 늘었는지 확인할 때 보는 개념은 무엇일까요?",
        answerId: "rpt-capa",
        choices: [
          { id: "rpt-capa", label: "생산능력 (CAPA)" },
          { id: "자본적지출", label: "자본적지출 (CAPEX)" },
          { id: "rpt-util", label: "가동률" },
          { id: "주당순이익-eps", label: "주당순이익 (EPS)" },
        ],
        note: "생산능력(CAPA)은 설비가 최대로 만들 수 있는 양이에요. 투자가 늘어도 생산능력이 바로 늘지는 않을 수 있어요.",
      },
      {
        type: "choice",
        depth: "term",
        question: "늘어난 생산능력이 실제 생산으로 이어지고 있는지 확인할 때 보는 지표는 무엇일까요?",
        answerId: "rpt-util",
        choices: [
          { id: "rpt-util", label: "가동률" },
          { id: "rpt-capa", label: "생산능력 (CAPA)" },
          { id: "자본적지출", label: "자본적지출 (CAPEX)" },
          { id: "소매판매", label: "소매판매" },
        ],
        note: "가동률은 가진 생산능력 가운데 실제로 얼마나 돌리고 있는지의 비율이에요. 설비가 늘어도 가동률이 낮으면 실적으로 바로 이어지지 않을 수 있어요.",
      },
      {
        type: "causal",
        title: "한 번에 연결하면",
        chain: ["CAPEX", "생산능력", "가동률", "실적"],
      },
      { type: "concepts", ids: ["자본적지출", "rpt-capa", "rpt-util"] },
    ],
  },
  {
    id: "bf-gdp-retail",
    kicker: "경기",
    minutes: 3,
    headline: "성장률은 올랐는데 체감경기는 달랐어요",
    subtitle: "국내총생산이 수출과 투자로 늘면, 가계가 느끼는 속도와 어긋날 수 있어요.",
    primaryTermIds: ["국내총생산-gdp", "소매판매", "경기"],
    sourceMode: "synthetic",
    contentMode: "synthetic",
    readingFormat: "market",
    reviewStatus: "published",
    difficulty: "core",
    sourceRefs: [SRC],
    evergreen: true,
    blocks: [
      {
        type: "p",
        text: "국내총생산 성장률이 전분기보다 높아졌다는 발표가 나왔어요. 그런데 같은 기간 소매판매는 크게 늘지 않았고, 체감경기 이야기와는 온도가 달랐어요.",
      },
      {
        type: "p",
        text: "수출이나 투자가 성장을 이끌면 생산 지표는 괜찮은데 가계 소비는 약할 수 있어요. 성장률 한 줄만 보면 그 구성이 가려져요.",
      },
      {
        type: "p",
        text: "다만 체감이 나쁘다고 성장률 숫자가 틀린 것은 아니에요. 소비·투자·수출이 성장에 얼마나 기여했는지를 나눠 봐야 해요.",
      },
      {
        type: "choice",
        depth: "term",
        question: "한 나라 안에서 일정 기간 생산된 재화와 서비스의 가치를 합한 지표는 무엇일까요?",
        answerId: "국내총생산-gdp",
        choices: [
          { id: "국내총생산-gdp", label: "국내총생산 (GDP)" },
          { id: "국민총소득-gni", label: "국민총소득 (GNI)" },
          { id: "경상수지", label: "경상수지" },
          { id: "외환보유액", label: "외환보유액" },
        ],
        note: "GDP는 국내에서 생산된 재화와 서비스의 가치를 합한 지표예요. GNI는 그 나라 국민이 국내외에서 벌어들인 소득의 합에 가까워요.",
      },
      {
        type: "choice",
        depth: "next",
        question: "GDP가 늘어난 이유를 확인하려면 무엇을 나눠 봐야 할까요?",
        answerId: "mix",
        choices: [
          { id: "mix", label: "소비·투자·수출 등이 성장에 얼마나 기여했는지" },
          { id: "one", label: "성장률 한 줄이면 구성은 볼 필요가 없다" },
          { id: "same", label: "GDP와 소매판매는 항상 같은 속도를 가리킨다" },
          { id: "feel", label: "체감이 나쁘면 성장률 숫자는 틀린 것이다" },
        ],
        note: "같은 성장률이라도 무엇이 성장을 이끌었는지에 따라 가계의 체감경기와 기업 실적은 다르게 나타날 수 있어요.",
      },
      {
        type: "causal",
        title: "한 번에 연결하면",
        chain: ["생산", "GDP", "소비", "체감 경기"],
      },
      { type: "concepts", ids: ["국내총생산-gdp", "소매판매", "경기"] },
    ],
  },
  {
    id: "bf-shareholder",
    kicker: "주주환원",
    minutes: 3,
    headline: "배당 확대 발표가 나왔지만, 주주환원은 아직 계획이었어요",
    subtitle: "발표와 실제 집행, 이익과 현금흐름은 나눠서 봐야 해요.",
    primaryTermIds: ["주주환원정책", "주당순이익-eps", "rpt-guidance"],
    sourceMode: "synthetic",
    contentMode: "synthetic",
    readingFormat: "earnings",
    reviewStatus: "published",
    difficulty: "core",
    sourceRefs: [SRC],
    evergreen: true,
    blocks: [
      {
        type: "p",
        text: "한 회사가 배당 확대와 자사주 매입 계획을 발표했어요. 발표 당일 주가는 올랐지만, 실제 집행 규모와 시기는 아직 나오지 않았어요.",
      },
      {
        type: "p",
        text: "발표 직후 시장은 환원 확대로 읽었어요. 하지만 아직 실제 배당이나 자사주 매입이 나간 것은 아니고, 회사가 앞으로 하겠다는 가이던스에 가까워요.",
      },
      {
        type: "p",
        text: "지속 여부를 보려면 실제 배당·자사주 집행과 주당순이익, 현금흐름을 확인해야 해요. 이익이 줄어들면 같은 환원 규모를 오래 유지하기 어려울 수 있어요.",
      },
      {
        type: "choice",
        depth: "term",
        question: "배당·자사주 매입 등으로 이익을 주주에게 돌리는 정책은 무엇일까요?",
        answerId: "주주환원정책",
        choices: [
          { id: "주주환원정책", label: "주주환원정책" },
          { id: "유상증자", label: "유상증자" },
          { id: "기업공개", label: "기업공개" },
          { id: "rpt-guidance", label: "가이던스" },
        ],
        note: "주주환원은 배당과 자사주 매입 등으로 이익을 주주에게 돌리는 정책이에요. 발표와 실제 집행은 구분해서 봐요.",
      },
      {
        type: "choice",
        depth: "next",
        question: "주주환원 확대 계획이 실제로 이행되고 있는지 확인하려면 무엇을 봐야 할까요?",
        answerId: "eps",
        choices: [
          { id: "eps", label: "실제 배당·자사주 집행과 이익·현금흐름" },
          { id: "word", label: "발표 문장만 보면 충분하다" },
          { id: "once", label: "환원 비율을 올리면 이익이 줄어도 지속된다" },
          { id: "price", label: "발표 당일 주가가 오르면 환원은 끝난 것이다" },
        ],
        note: "계획이 발표돼도 실제 배당·자사주 집행과 이익·현금흐름을 확인해야 지속 여부를 판단할 수 있어요.",
      },
      {
        type: "causal",
        title: "한 번에 연결하면",
        chain: ["이익", "주주환원 계획", "실제 배당·자사주", "주가"],
      },
      { type: "concepts", ids: ["주주환원정책", "주당순이익-eps", "rpt-guidance"] },
    ],
  },
  {
    id: "bf-bond-rates",
    kicker: "국채·금리",
    minutes: 3,
    headline: "국채금리가 오르자 기존 채권 가격이 내렸어요",
    subtitle: "이미 발행된 채권의 이자는 고정돼 있어, 시장금리가 오르면 가격이 조정돼요.",
    primaryTermIds: ["국채", "만기수익률", "신용스프레드"],
    supportTermIds: ["듀레이션"],
    sourceMode: "synthetic",
    contentMode: "synthetic",
    readingFormat: "market",
    reviewStatus: "published",
    difficulty: "core",
    sourceRefs: [SRC],
    evergreen: true,
    blocks: [
      {
        type: "p",
        text: "국채금리가 오르자 이미 발행된 채권 가격이 하락했어요. 새 채권은 더 높은 이자를 줄 수 있는데, 기존 채권의 표면금리는 그대로이기 때문이에요.",
      },
      {
        type: "p",
        text: "시장은 현재 가격으로 만기까지 보유할 때 기대하는 만기수익률로 그 조정을 읽었어요. 같은 폭으로 금리가 올라도 만기가 긴 채권의 가격이 더 크게 움직일 수 있어요.",
      },
      {
        type: "p",
        text: "국채금리는 거의 그대로인데 회사채금리만 올랐다면 신용스프레드가 벌어진 것이에요. 기업의 신용위험에 대해 더 높은 금리를 요구한다는 해석이 붙어요. 다만 환율만으로 그 차이를 단정할 수는 없어요.",
      },
      {
        type: "choice",
        depth: "term",
        question: "현재 가격으로 채권을 사서 만기까지 보유할 때 기대하는 수익률은 무엇일까요?",
        answerId: "만기수익률",
        choices: [
          { id: "만기수익률", label: "만기수익률" },
          { id: "표면금리", label: "표면금리" },
          { id: "기준금리", label: "기준금리" },
          { id: "지급준비제도", label: "지급준비제도" },
        ],
        note: "표면금리는 채권 발행 시 정해진 이자율이에요. 만기수익률은 현재 가격으로 매수해 만기까지 보유할 때 기대하는 수익률이에요.",
      },
      {
        type: "choice",
        depth: "cause",
        question: "국채와 회사채 금리 차이가 벌어진다는 것은 무엇을 뜻할까요?",
        answerId: "spread",
        choices: [
          { id: "spread", label: "신용위험에 대해 요구되는 추가 금리가 커진 것" },
          { id: "same", label: "국채와 회사채 금리는 항상 같이 움직이므로 차이는 의미가 없다" },
          { id: "div", label: "배당을 늘리면 회사채 스프레드는 반드시 줄어든다" },
          { id: "fx", label: "환율만 보면 신용 스프레드는 결정된다" },
        ],
        note: "국채금리는 비교적 신용위험이 낮은 금리에 가깝고, 회사채에는 기업의 신용위험이 더해져요.",
      },
      {
        type: "causal",
        title: "한 번에 연결하면",
        chain: ["시장금리 상승", "만기수익률", "채권가격 하락", "신용스프레드"],
      },
      { type: "concepts", ids: ["국채", "만기수익률", "신용스프레드"] },
    ],
  },
  {
    id: "bf-supply-price",
    kicker: "공급·물가",
    minutes: 3,
    headline: "공급이 줄자 생산자 가격이 먼저 올랐어요",
    subtitle: "수요가 그대로여도 원자재와 부품이 막히면 물가 압력이 생길 수 있어요.",
    primaryTermIds: ["인플레이션", "생산자물가지수-ppi", "스태그플레이션"],
    sourceMode: "synthetic",
    contentMode: "synthetic",
    readingFormat: "industry",
    reviewStatus: "published",
    difficulty: "core",
    sourceRefs: [SRC],
    evergreen: true,
    blocks: [
      {
        type: "p",
        text: "원자재와 부품 공급이 줄자 생산자물가지수가 먼저 올랐어요. 수요가 크게 늘지 않았는데도 생산 단계 가격이 움직인 것이에요.",
      },
      {
        type: "p",
        text: "이 비용이 소비자 가격에 전가되면 인플레이션 압력으로 이어질 수 있어요. 다만 전가되는 폭은 업종과 재고에 따라 달라요.",
      },
      {
        type: "p",
        text: "성장은 약한데 물가만 오르는 구간도 있어요. 그때를 스태그플레이션으로 부르며, 금리만 내려서 해결된다고 보기 어려워요. 공급 제약이 남아 있는지를 함께 봐야 해요.",
      },
      {
        type: "choice",
        depth: "term",
        question: "생산자가 거래하는 상품과 서비스의 가격 변화를 보여주는 지수는 무엇일까요?",
        answerId: "생산자물가지수-ppi",
        choices: [
          { id: "생산자물가지수-ppi", label: "생산자물가지수 (PPI)" },
          { id: "소비자물가지수-cpi", label: "소비자물가지수 (CPI)" },
          { id: "소매판매", label: "소매판매" },
          { id: "실업률", label: "실업률" },
        ],
        note: "생산자물가지수(PPI)는 생산자가 거래하는 상품과 서비스의 가격 변화를 보여줘요. 생산 단계의 가격 상승이 소비자 가격에 얼마나 전가되는지는 별도로 확인해야 해요.",
      },
      {
        type: "choice",
        depth: "next",
        question: "경기 둔화와 물가 상승이 동시에 나타나는 상황을 무엇이라고 할까요?",
        answerId: "stag",
        choices: [
          { id: "stag", label: "스태그플레이션" },
          { id: "always", label: "성장이 약하면 물가는 반드시 내려간다" },
          { id: "cpi-only", label: "PPI는 볼 필요 없이 CPI 한 줄이면 충분하다" },
          { id: "ignore", label: "공급 제약은 물가와 무관하다" },
        ],
        note: "수요가 줄어도 공급이 막혀 있으면 물가가 오를 수 있어요. 성장과 물가를 한 방향으로만 묶지 않아요.",
      },
      {
        type: "causal",
        title: "한 번에 연결하면",
        chain: ["공급 제약", "생산자 가격", "소비자 물가", "성장"],
      },
      { type: "concepts", ids: ["인플레이션", "생산자물가지수-ppi", "스태그플레이션"] },
    ],
  },
  {
    id: "bf-credit-spread",
    kicker: "신용·금리",
    minutes: 3,
    headline: "국채 금리는 내렸는데 회사채 금리는 더 올랐어요",
    subtitle: "기준이 되는 금리와 기업이 실제로 빌리는 금리는 같이 움직이지 않을 수 있어요.",
    primaryTermIds: ["신용스프레드", "회사채", "국채"],
    supportTermIds: ["신용위험"],
    sourceMode: "synthetic",
    contentMode: "synthetic",
    readingFormat: "market",
    reviewStatus: "published",
    difficulty: "core",
    sourceRefs: [SRC],
    evergreen: true,
    blocks: [
      {
        type: "p",
        text: "국채 금리는 내렸는데, 같은 만기 회사채 금리는 오히려 올랐어요. 시장 일부는 금리가 내려 자금 조달이 쉬워졌다고 읽었어요.",
      },
      {
        type: "p",
        text: "그런데 기업이 빌리는 금리는 국채 금리에 신용위험을 더한 값이에요. 국채는 내렸어도 그 가산 폭이 커지면 회사채 금리는 오를 수 있어요. 이 차이를 신용스프레드로 봐요.",
      },
      {
        type: "cloze",
        before: "국채 금리는 내렸는데 회사채 금리가 올랐다면, 둘의 차이인 ",
        after: "가 벌어진 것으로 읽혀요.",
        question: "국채와 회사채 금리 차이가 커진 상황을 무엇으로 읽을까요?",
        answerId: "spread",
        choices: [
          { id: "spread", label: "신용스프레드" },
          { id: "dur", label: "듀레이션" },
          { id: "coupon", label: "표면금리" },
          { id: "reserve", label: "지급준비율" },
        ],
        note: "신용스프레드는 국채 같은 기준 금리와 회사채 금리의 차이예요. 기준 금리가 내려도 스프레드가 더 벌어지면 기업이 부담하는 이자는 커질 수 있어요.",
      },
      {
        type: "p",
        text: "다만 스프레드가 벌어졌다고 모든 기업의 신용이 나빠진 것은 아니에요. 특정 업종·등급만 움직였는지, 채권 수급이 꼬였는지도 같이 봐야 해요.",
      },
      {
        type: "choice",
        depth: "next",
        question: "회사채 금리가 국채와 다르게 움직이면 다음에 무엇을 보는 게 좋을까요?",
        answerId: "grade",
        choices: [
          { id: "grade", label: "신용등급·업종별 스프레드가 같이 벌어졌는지" },
          { id: "all", label: "국채 금리만 보면 회사채 금리도 자동으로 안다" },
          { id: "same", label: "스프레드가 벌어지면 모든 기업의 부도가 확정된다" },
          { id: "ignore", label: "회사채 금리는 실적과 무관하므로 보지 않아도 된다" },
        ],
        note: "평균 스프레드 한 줄은 착시가 날 수 있어요. 어떤 등급·업종이 벌어졌는지 봐야 자금 조달 부담이 어디에 있는지 보여요.",
      },
      {
        type: "causal",
        title: "한 번에 연결하면",
        chain: ["국채 금리", "신용스프레드", "회사채 금리", "기업 이자 부담"],
      },
      { type: "concepts", ids: ["신용스프레드", "회사채", "국채"] },
    ],
  },
  {
    id: "bf-nominal-price",
    kicker: "금리·물가",
    minutes: 3,
    headline: "금리는 내렸는데, 물가를 감안하면 돈의 값은 덜 싸졌어요",
    subtitle: "표시된 금리만 보면 싸진 것 같아도, 물가가 같이 낮아지지 않으면 실질 부담은 다를 수 있어요.",
    primaryTermIds: ["명목금리", "인플레이션", "기준금리"],
    sourceMode: "synthetic",
    contentMode: "synthetic",
    readingFormat: "policy",
    reviewStatus: "published",
    difficulty: "core",
    sourceRefs: [SRC],
    evergreen: true,
    blocks: [
      {
        type: "p",
        text: "기준금리가 내리자 예금·대출에 붙는 명목금리도 따라 내렸어요. 일부는 이제 돈을 빌리기 쉬워졌다고 읽었어요.",
      },
      {
        type: "p",
        text: "그런데 물가 상승세가 금리만큼 빨리 낮아지지 않으면, 표시된 금리가 내려도 물가를 감안한 돈의 값은 덜 싸질 수 있어요. 명목금리는 물가를 빼기 전의 숫자예요.",
      },
      {
        type: "cloze",
        before: "물가 변화를 빼기 전에 화면에 적히는 금리를 ",
        after: "라고 불러요.",
        question: "물가를 감안하기 전의 금리를 무엇이라고 할까요?",
        answerId: "nominal",
        choices: [
          { id: "nominal", label: "명목금리" },
          { id: "core", label: "근원물가" },
          { id: "spread", label: "신용스프레드" },
          { id: "gap", label: "GDP갭" },
        ],
        note: "명목금리는 물가 상승을 빼기 전의 표시 금리예요. 금리가 내려도 인플레이션이 그대로면 실질적인 돈의 값은 다르게 읽혀요.",
      },
      {
        type: "p",
        text: "그래서 금리 인하 한 줄만으로 ‘돈 값이 싸졌다’고 단정하기는 어려워요. 같은 기간 인플레이션이 얼마나 낮아졌는지도 같이 봐야 해요.",
      },
      {
        type: "choice",
        depth: "next",
        question: "명목금리가 내렸을 때 함께 보면 좋은 것은 무엇일까요?",
        answerId: "infl",
        choices: [
          { id: "infl", label: "같은 기간 인플레이션이 얼마나 낮아졌는지" },
          { id: "only", label: "기준금리 숫자 하나면 돈의 값이 확정된다" },
          { id: "same", label: "명목금리가 내리면 물가도 반드시 같이 내린다" },
          { id: "ignore", label: "물가는 금리 판단과 무관하다" },
        ],
        note: "표시 금리가 내려도 물가가 그대로면 실질 부담은 덜 줄어들 수 있어요. 금리와 인플레이션을 같이 봐요.",
      },
      {
        type: "causal",
        title: "한 번에 연결하면",
        chain: ["기준금리", "명목금리", "인플레이션", "실질 부담"],
      },
      { type: "concepts", ids: ["명목금리", "인플레이션", "기준금리"] },
    ],
  },
  {
    id: "bf-dsr-home",
    kicker: "가계·부동산",
    minutes: 3,
    headline: "집값은 꺾였는데 원리금 부담은 바로 줄지 않았어요",
    subtitle: "담보 가치와 갚아야 할 원리금은 같은 속도로 움직이지 않아요.",
    primaryTermIds: ["총부채원리금상환비율-dsr", "담보인정비율-ltv", "모기지대출"],
    sourceMode: "synthetic",
    contentMode: "synthetic",
    readingFormat: "policy",
    reviewStatus: "published",
    difficulty: "core",
    sourceRefs: [SRC],
    evergreen: true,
    blocks: [
      {
        type: "p",
        text: "주택 가격이 내리자 담보인정비율(LTV)로 본 대출 여력은 줄어 보였어요. 그런데 이미 받은 모기지대출의 원리금은 바로 줄지 않았어요.",
      },
      {
        type: "p",
        text: "집값은 담보의 크기이고, 매달 나가는 원리금은 소득 대비 상환 부담이에요. 후자는 총부채원리금상환비율(DSR)로 봐요. 가격이 꺾여도 금리가 높거나 만기가 짧으면 상환 부담은 남을 수 있어요.",
      },
      {
        type: "cloze",
        before: "소득에서 원리금이 차지하는 비중은 ",
        after: "로 봐요.",
        question: "갚아야 할 원리금이 소득에서 얼마나 차지하는지 보는 비율은 무엇일까요?",
        answerId: "dsr",
        choices: [
          { id: "dsr", label: "DSR" },
          { id: "ltv", label: "LTV" },
          { id: "per", label: "PER" },
          { id: "roe", label: "ROE" },
        ],
        note: "DSR은 소득 대비 원리금 상환 부담이에요. LTV는 집값 대비 대출 비율이라, 담보가 줄어도 매달 나가는 돈이 바로 줄지는 않아요.",
      },
      {
        type: "p",
        text: "그래서 집값 한 줄만으로 가계 부담이 줄었다고 보기 어려워요. 변동금리인지, 만기를 늘렸는지, 소득이 같이 움직였는지도 봐야 해요.",
      },
      {
        type: "choice",
        depth: "next",
        question: "집값이 내린 뒤에 가계 대출 부담을 보려면 무엇을 같이 보는 게 좋을까요?",
        answerId: "both",
        choices: [
          { id: "both", label: "DSR과 금리·만기 조건" },
          { id: "price", label: "집값만 보면 원리금 부담도 자동으로 안다" },
          { id: "ltv-only", label: "LTV가 낮아지면 DSR도 반드시 낮아진다" },
          { id: "ignore", label: "모기지대출은 소득과 무관하다" },
        ],
        note: "담보 비율과 상환 부담은 다른 질문이에요. 집값이 내려도 금리와 만기가 그대로면 매달 나가는 돈은 남을 수 있어요.",
      },
      {
        type: "causal",
        title: "한 번에 연결하면",
        chain: ["집값", "LTV", "모기지 원리금", "DSR"],
      },
      { type: "concepts", ids: ["총부채원리금상환비율-dsr", "담보인정비율-ltv", "모기지대출"] },
    ],
  },
  {
    id: "bf-yield-curve",
    kicker: "금리 곡선",
    minutes: 3,
    headline: "단기금리는 내렸는데 장기금리는 거의 안 움직였어요",
    subtitle: "만기가 다른 금리는 같은 뉴스를 다르게 반영할 수 있어요.",
    primaryTermIds: ["장단기금리차", "수익률곡선", "국채"],
    sourceMode: "synthetic",
    contentMode: "synthetic",
    readingFormat: "market",
    reviewStatus: "published",
    difficulty: "core",
    sourceRefs: [SRC],
    evergreen: true,
    blocks: [
      {
        type: "p",
        text: "정책금리 인하 기대가 커지자 만기가 짧은 국채 금리는 내렸어요. 그런데 만기가 긴 국채 금리는 거의 그대로였어요.",
      },
      {
        type: "p",
        text: "만기별 금리를 이은 그림이 수익률곡선이에요. 짧은 금리와 긴 금리의 차이를 장단기금리차로 봐요. 짧은 쪽만 내리면 그 차이가 줄어들거나 뒤집힐 수 있어요.",
      },
      {
        type: "cloze",
        before: "만기가 짧은 금리와 긴 금리의 차이를 ",
        after: "라고 불러요.",
        question: "단기 금리와 장기 금리의 차이를 무엇이라고 할까요?",
        answerId: "gap",
        choices: [
          { id: "gap", label: "장단기금리차" },
          { id: "cpi", label: "소비자물가" },
          { id: "roe", label: "자기자본이익률" },
          { id: "ltv", label: "담보인정비율" },
        ],
        note: "장단기금리차는 만기가 다른 금리의 간격이에요. 짧은 금리만 내리면 곡선이 평평해지거나 기울기가 달라져 보여요.",
      },
      {
        type: "p",
        text: "곡선이 평평해졌다고 경기가 바로 꺾인 것은 아니에요. 수급, 물가 기대, 해외 금리가 장기물에 더 크게 남았을 수 있어요. 한 번의 기울기만으로 단정하지 않아요.",
      },
      {
        type: "choice",
        depth: "next",
        question: "단기 금리만 움직였을 때 다음에 보면 좋은 것은 무엇일까요?",
        answerId: "curve",
        choices: [
          { id: "curve", label: "수익률곡선 전체와 물가·성장 기대" },
          { id: "short", label: "단기 금리 한 줄이면 장기 금리도 확정된다" },
          { id: "always", label: "장단기금리차가 줄어들면 다음 달 침체가 확정된다" },
          { id: "ignore", label: "만기가 다른 금리는 같은 숫자라 나눠 볼 필요가 없다" },
        ],
        note: "짧은 금리는 정책 기대를, 긴 금리는 물가와 성장 기대를 더 담는 경우가 많아요. 곡선 전체를 봐야 해요.",
      },
      {
        type: "causal",
        title: "한 번에 연결하면",
        chain: ["정책 기대", "단기 금리", "장기 금리", "장단기금리차"],
      },
      { type: "concepts", ids: ["장단기금리차", "수익률곡선", "국채"] },
    ],
  },
  {
    id: "bf-per-pbr",
    kicker: "배수 읽기",
    minutes: 3,
    headline: "이익은 줄었는데 주가순자산비율은 올랐어요",
    subtitle: "같은 주가도 나누는 숫자가 바뀌면 비싸 보이거나 싸 보여요.",
    primaryTermIds: ["주가수익비율-per", "주가순자산비율-pbr", "자기자본이익률-roe"],
    sourceMode: "synthetic",
    contentMode: "synthetic",
    readingFormat: "earnings",
    reviewStatus: "published",
    difficulty: "core",
    sourceRefs: [SRC],
    evergreen: true,
    blocks: [
      {
        type: "p",
        text: "한 기업의 주가는 거의 그대로인데, 주가수익비율(PER)은 높아 보이고 주가순자산비율(PBR)은 따로 움직였어요. 이익이 줄어 분모가 작아진 영향이 컸어요.",
      },
      {
        type: "p",
        text: "PER은 주가를 이익으로 나눈 배수예요. 이익이 일시적으로 줄면 배수가 비싸 보일 수 있어요. PBR은 주가를 순자산으로 나누고, 자기자본이익률(ROE)이 낮아지면 같은 PBR도 다르게 읽혀요.",
      },
      {
        type: "cloze",
        before: "주가를 이익으로 나눈 배수가 높아 보일 때는, 분모인 이익이 ",
        after: " 경우를 먼저 의심해요.",
        question: "주가는 비슷한데 PER이 높아 보일 때 먼저 의심할 일은 무엇일까요?",
        answerId: "earn",
        choices: [
          { id: "earn", label: "줄어든" },
          { id: "up", label: "늘어난" },
          { id: "fx", label: "환율과 무관한" },
          { id: "gone", label: "사라진" },
        ],
        note: "PER은 주가÷이익이에요. 이익이 줄면 같은 주가에도 배수가 올라 보여요. 그래서 배수가 높아졌다고 바로 고평가라고 단정하지 않아요.",
      },
      {
        type: "p",
        text: "다만 PER만 보면 자산 가치와 수익성을 놓쳐요. PBR과 ROE를 같이 봐야, 지금 비싼 게 이익 부진 때문인지 자산 대비 기대 때문인지 갈려요.",
      },
      {
        type: "choice",
        depth: "next",
        question: "PER이 높아 보일 때 함께 보면 좋은 것은 무엇일까요?",
        answerId: "pair",
        choices: [
          { id: "pair", label: "이익의 질, PBR, ROE" },
          { id: "only", label: "PER 숫자 하나면 고평가가 확정된다" },
          { id: "same", label: "PER과 PBR은 항상 같이 움직인다" },
          { id: "ignore", label: "이익이 줄어도 배수는 보지 않아도 된다" },
        ],
        note: "이익이 일시적으로 줄면 PER이 왜곡돼요. 자산 대비 가격(PBR)과 자본이 돈을 얼마나 벌었는지(ROE)를 같이 봐요.",
      },
      {
        type: "causal",
        title: "한 번에 연결하면",
        chain: ["이익 변화", "PER", "순자산·ROE", "PBR"],
      },
      { type: "concepts", ids: ["주가수익비율-per", "주가순자산비율-pbr", "자기자본이익률-roe"] },
    ],
  },
];

let extraBriefings: LearningBriefing[] = [];

export function registerExtraBriefings(list: LearningBriefing[]): void {
  extraBriefings = list.filter((b) => b.reviewStatus !== "draft");
}

export function allBriefings(): LearningBriefing[] {
  const seen = new Set(LEARNING_BRIEFINGS.map((b) => b.id));
  return [...LEARNING_BRIEFINGS, ...extraBriefings.filter((b) => !seen.has(b.id))];
}

export function briefingById(id: string): LearningBriefing | undefined {
  return allBriefings().find((b) => b.id === id);
}

export function nextBriefing(seenIds: string[]): LearningBriefing {
  const pool = allBriefings();
  const unseen = pool.find((b) => !seenIds.includes(b.id));
  if (unseen) return unseen;
  const i = new Date().getDay() % pool.length;
  return pool[i];
}

export const PILOT_TERM_IDS: string[] = [
  ...new Set(LEARNING_BRIEFINGS.flatMap((b) => b.primaryTermIds)),
];
